linters:
  enable-all: true
  disable:
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - funlen
    - paralleltest
    - gochecknoglobals
    - thelper
    - godox
    - exhaustruct
    - wsl
    - gci
    - nolintlint
    - maintidx
    - ireturn
    - bodyclose
    - depguard
    - wrapcheck
    - perfsprint
    - contextcheck
    - gomnd
    - execinquery
linters-settings:
  varnamelen:
    ignore-names:
      - form
      - to
      - ok
      - fs
      - ca