version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - godox
    - ireturn
    - maintidx
    - nolintlint
    - paralleltest
    - perfsprint
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    varnamelen:
      ignore-names:
        - form
        - to
        - ok
        - fs
        - ca
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
