run:
  skip-dirs:
    - testing
    - dist
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - nosnakecase
    - interfacer
    - scopelint
    - maligned
    - varcheck
    - golint
    - structcheck
    - deadcode
    - ifshort
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - funlen
    - paralleltest
    - gochecknoglobals
    - thelper
    - godox
    - exhaustruct
    - wsl
    - gci
    - gofmt
    - gofumpt
    - nolintlint
    - tagliatelle
linters-settings:
  varnamelen:
    ignore-names:
      - form
      - to
presets:
  - bugs
  - comment
  - complexity
  - error
  - format
  - import
  - metalinter
  - module
  - performance
  - style
  - test
  - unused
