# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: uncors
before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
    ignore:
      - goos: darwin
        goarch: '386'
    main: '.'
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    tags: [ release ]
checksum:
  name_template: 'checksums.txt'
source:
  enabled: false
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "evg4b/{{ .ProjectName }}:{{ .Version }}"
      - "evg4b/{{ .ProjectName }}:latest"
      - "ghcr.io/evg4b/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/evg4b/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source='https://github.com/evg4b/uncors'"
      - "--label=org.opencontainers.image.description='A simple dev HTTP/HTTPS proxy for replacing CORS headers.'"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "evg4b/{{ .ProjectName }}:{{ .Version }}"
      - "evg4b/{{ .ProjectName }}:latest"
      - "ghcr.io/evg4b/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/evg4b/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source='https://github.com/evg4b/uncors'"
      - "--label=org.opencontainers.image.description='A simple dev HTTP/HTTPS proxy for replacing CORS headers.'"
docker_manifests:
  - name_template: evg4b/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - evg4b/{{ .ProjectName }}:{{ .Version }}
  - name_template: evg4b/{{ .ProjectName }}:latest
    image_templates:
      - evg4b/{{ .ProjectName }}:latest
brews:
  - name: uncors
    description: A simple dev HTTP/HTTPS reverse proxy for replacing CORS headers.
    license: MIT
    homepage: https://github.com/evg4b/uncors
    directory: Formula
    repository:
      owner: evg4b
      name: homebrew-tap
      token: "{{ .Env.ACCOUNT_GITHUB_TOKEN }}"
    test:
      system "#{bin}/uncors", "--help"
    commit_author:
      name: Evgeny Abramovich
      email: evg.abramovitch@gmail.com
scoops:
  - name: uncors
    repository:
      owner: evg4b
      name: scoop-bucket
      branch: main
      token: "{{ .Env.ACCOUNT_GITHUB_TOKEN }}"
    directory: bucket
    commit_author:
      name: Evgeny Abramovich
      email: evg.abramovitch@gmail.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/evg4b/uncors
    description: A simple dev HTTP/HTTPS reverse proxy for replacing CORS headers.
    license: MIT
