http-port: 8080
mappings:
  - from: localhost
    to: https://github.com
    cache:
      - /api/**
    mocks:
      - path: /demo
        method: GET
        response:
          code: 200
          raw: 'OK'
    statics:
      - path: /cc
        dir: /Users/evg4b/Documents/uncors
        index: main.go