http-port: 8080
mappings:
  http://demo1: https://demo1.com
  http://other-demo2: https://demo2.io
proxy: localhost:8080
debug: true
https-port: 8081
cert-file: /cert-file.pem
key-file: /key-file.key
mocks:
  - path: /demo
    method: POST
    queries:
      foo: bar
    headers:
      Accept-Encoding: deflate
    response:
      code: 201
      headers:
        Accept-Encoding: deflate
      raw-content: demo
      file: /demo.txt
