name: Feature Request
description: Suggest a new feature or enhancement for UNCORS
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like UNCORS to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which category does this feature fall under?
      options:
        - CORS handling
        - Request/Response manipulation
        - Configuration
        - Performance
        - Developer experience
        - Documentation
        - Script handler (Lua)
        - Static file serving
        - Caching
        - Proxy functionality
        - TLS/HTTPS
        - Logging/Debugging
        - CLI interface
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would benefit you and others.
      placeholder: This would help when...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: If applicable, provide examples of how this feature would work (code snippets, configuration examples, etc.).
      placeholder: |
        ```yaml
        # Example configuration
        new-feature:
          enabled: true
          option: value
        ```
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical / blocking
    validations:
      required: true

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to contribute to the implementation of this feature?
      options:
        - Yes, I can implement this feature
        - Yes, I can help with implementation
        - I can provide guidance/feedback
        - No, I cannot contribute to implementation
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched existing issues and pull requests to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with UNCORS's purpose as a development proxy tool
          required: true
        - label: I have provided sufficient details about the use case and expected behavior
          required: true
