package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/evg4b/uncors/internal/contracts.HttpClient -o ./http_client_mock.go -n HttpClientMock

import (
	"net/http"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// HttpClientMock implements contracts.HttpClient
type HttpClientMock struct {
	t minimock.Tester

	funcDo          func(req *http.Request) (rp1 *http.Response, err error)
	inspectFuncDo   func(req *http.Request)
	afterDoCounter  uint64
	beforeDoCounter uint64
	DoMock          mHttpClientMockDo
}

// NewHttpClientMock returns a mock for contracts.HttpClient
func NewHttpClientMock(t minimock.Tester) *HttpClientMock {
	m := &HttpClientMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DoMock = mHttpClientMockDo{mock: m}
	m.DoMock.callArgs = []*HttpClientMockDoParams{}

	return m
}

type mHttpClientMockDo struct {
	mock               *HttpClientMock
	defaultExpectation *HttpClientMockDoExpectation
	expectations       []*HttpClientMockDoExpectation

	callArgs []*HttpClientMockDoParams
	mutex    sync.RWMutex
}

// HttpClientMockDoExpectation specifies expectation struct of the HttpClient.Do
type HttpClientMockDoExpectation struct {
	mock    *HttpClientMock
	params  *HttpClientMockDoParams
	results *HttpClientMockDoResults
	Counter uint64
}

// HttpClientMockDoParams contains parameters of the HttpClient.Do
type HttpClientMockDoParams struct {
	req *http.Request
}

// HttpClientMockDoResults contains results of the HttpClient.Do
type HttpClientMockDoResults struct {
	rp1 *http.Response
	err error
}

// Expect sets up expected params for HttpClient.Do
func (mmDo *mHttpClientMockDo) Expect(req *http.Request) *mHttpClientMockDo {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("HttpClientMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &HttpClientMockDoExpectation{}
	}

	mmDo.defaultExpectation.params = &HttpClientMockDoParams{req}
	for _, e := range mmDo.expectations {
		if minimock.Equal(e.params, mmDo.defaultExpectation.params) {
			mmDo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDo.defaultExpectation.params)
		}
	}

	return mmDo
}

// Inspect accepts an inspector function that has same arguments as the HttpClient.Do
func (mmDo *mHttpClientMockDo) Inspect(f func(req *http.Request)) *mHttpClientMockDo {
	if mmDo.mock.inspectFuncDo != nil {
		mmDo.mock.t.Fatalf("Inspect function is already set for HttpClientMock.Do")
	}

	mmDo.mock.inspectFuncDo = f

	return mmDo
}

// Return sets up results that will be returned by HttpClient.Do
func (mmDo *mHttpClientMockDo) Return(rp1 *http.Response, err error) *HttpClientMock {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("HttpClientMock.Do mock is already set by Set")
	}

	if mmDo.defaultExpectation == nil {
		mmDo.defaultExpectation = &HttpClientMockDoExpectation{mock: mmDo.mock}
	}
	mmDo.defaultExpectation.results = &HttpClientMockDoResults{rp1, err}
	return mmDo.mock
}

//Set uses given function f to mock the HttpClient.Do method
func (mmDo *mHttpClientMockDo) Set(f func(req *http.Request) (rp1 *http.Response, err error)) *HttpClientMock {
	if mmDo.defaultExpectation != nil {
		mmDo.mock.t.Fatalf("Default expectation is already set for the HttpClient.Do method")
	}

	if len(mmDo.expectations) > 0 {
		mmDo.mock.t.Fatalf("Some expectations are already set for the HttpClient.Do method")
	}

	mmDo.mock.funcDo = f
	return mmDo.mock
}

// When sets expectation for the HttpClient.Do which will trigger the result defined by the following
// Then helper
func (mmDo *mHttpClientMockDo) When(req *http.Request) *HttpClientMockDoExpectation {
	if mmDo.mock.funcDo != nil {
		mmDo.mock.t.Fatalf("HttpClientMock.Do mock is already set by Set")
	}

	expectation := &HttpClientMockDoExpectation{
		mock:   mmDo.mock,
		params: &HttpClientMockDoParams{req},
	}
	mmDo.expectations = append(mmDo.expectations, expectation)
	return expectation
}

// Then sets up HttpClient.Do return parameters for the expectation previously defined by the When method
func (e *HttpClientMockDoExpectation) Then(rp1 *http.Response, err error) *HttpClientMock {
	e.results = &HttpClientMockDoResults{rp1, err}
	return e.mock
}

// Do implements contracts.HttpClient
func (mmDo *HttpClientMock) Do(req *http.Request) (rp1 *http.Response, err error) {
	mm_atomic.AddUint64(&mmDo.beforeDoCounter, 1)
	defer mm_atomic.AddUint64(&mmDo.afterDoCounter, 1)

	if mmDo.inspectFuncDo != nil {
		mmDo.inspectFuncDo(req)
	}

	mm_params := &HttpClientMockDoParams{req}

	// Record call args
	mmDo.DoMock.mutex.Lock()
	mmDo.DoMock.callArgs = append(mmDo.DoMock.callArgs, mm_params)
	mmDo.DoMock.mutex.Unlock()

	for _, e := range mmDo.DoMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmDo.DoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDo.DoMock.defaultExpectation.Counter, 1)
		mm_want := mmDo.DoMock.defaultExpectation.params
		mm_got := HttpClientMockDoParams{req}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDo.t.Errorf("HttpClientMock.Do got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDo.DoMock.defaultExpectation.results
		if mm_results == nil {
			mmDo.t.Fatal("No results are set for the HttpClientMock.Do")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmDo.funcDo != nil {
		return mmDo.funcDo(req)
	}
	mmDo.t.Fatalf("Unexpected call to HttpClientMock.Do. %v", req)
	return
}

// DoAfterCounter returns a count of finished HttpClientMock.Do invocations
func (mmDo *HttpClientMock) DoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.afterDoCounter)
}

// DoBeforeCounter returns a count of HttpClientMock.Do invocations
func (mmDo *HttpClientMock) DoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDo.beforeDoCounter)
}

// Calls returns a list of arguments used in each call to HttpClientMock.Do.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDo *mHttpClientMockDo) Calls() []*HttpClientMockDoParams {
	mmDo.mutex.RLock()

	argCopy := make([]*HttpClientMockDoParams, len(mmDo.callArgs))
	copy(argCopy, mmDo.callArgs)

	mmDo.mutex.RUnlock()

	return argCopy
}

// MinimockDoDone returns true if the count of the Do invocations corresponds
// the number of defined expectations
func (m *HttpClientMock) MinimockDoDone() bool {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		return false
	}
	return true
}

// MinimockDoInspect logs each unmet expectation
func (m *HttpClientMock) MinimockDoInspect() {
	for _, e := range m.DoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to HttpClientMock.Do with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		if m.DoMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to HttpClientMock.Do")
		} else {
			m.t.Errorf("Expected call to HttpClientMock.Do with params: %#v", *m.DoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDo != nil && mm_atomic.LoadUint64(&m.afterDoCounter) < 1 {
		m.t.Error("Expected call to HttpClientMock.Do")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *HttpClientMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockDoInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *HttpClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *HttpClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDoDone()
}
