// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/evg4b/uncors/internal/contracts.Output -o output_mock.go -n OutputMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OutputMock implements mm_contracts.Output
type OutputMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcError          func(msg any)
	funcErrorOrigin    string
	inspectFuncError   func(msg any)
	afterErrorCounter  uint64
	beforeErrorCounter uint64
	ErrorMock          mOutputMockError

	funcErrorf          func(msg string, args ...any)
	funcErrorfOrigin    string
	inspectFuncErrorf   func(msg string, args ...any)
	afterErrorfCounter  uint64
	beforeErrorfCounter uint64
	ErrorfMock          mOutputMockErrorf

	funcInfo          func(msg any)
	funcInfoOrigin    string
	inspectFuncInfo   func(msg any)
	afterInfoCounter  uint64
	beforeInfoCounter uint64
	InfoMock          mOutputMockInfo
}

// NewOutputMock returns a mock for mm_contracts.Output
func NewOutputMock(t minimock.Tester) *OutputMock {
	m := &OutputMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ErrorMock = mOutputMockError{mock: m}
	m.ErrorMock.callArgs = []*OutputMockErrorParams{}

	m.ErrorfMock = mOutputMockErrorf{mock: m}
	m.ErrorfMock.callArgs = []*OutputMockErrorfParams{}

	m.InfoMock = mOutputMockInfo{mock: m}
	m.InfoMock.callArgs = []*OutputMockInfoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOutputMockError struct {
	optional           bool
	mock               *OutputMock
	defaultExpectation *OutputMockErrorExpectation
	expectations       []*OutputMockErrorExpectation

	callArgs []*OutputMockErrorParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OutputMockErrorExpectation specifies expectation struct of the Output.Error
type OutputMockErrorExpectation struct {
	mock               *OutputMock
	params             *OutputMockErrorParams
	paramPtrs          *OutputMockErrorParamPtrs
	expectationOrigins OutputMockErrorExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// OutputMockErrorParams contains parameters of the Output.Error
type OutputMockErrorParams struct {
	msg any
}

// OutputMockErrorParamPtrs contains pointers to parameters of the Output.Error
type OutputMockErrorParamPtrs struct {
	msg *any
}

// OutputMockErrorOrigins contains origins of expectations of the Output.Error
type OutputMockErrorExpectationOrigins struct {
	origin    string
	originMsg string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmError *mOutputMockError) Optional() *mOutputMockError {
	mmError.optional = true
	return mmError
}

// Expect sets up expected params for Output.Error
func (mmError *mOutputMockError) Expect(msg any) *mOutputMockError {
	if mmError.mock.funcError != nil {
		mmError.mock.t.Fatalf("OutputMock.Error mock is already set by Set")
	}

	if mmError.defaultExpectation == nil {
		mmError.defaultExpectation = &OutputMockErrorExpectation{}
	}

	if mmError.defaultExpectation.paramPtrs != nil {
		mmError.mock.t.Fatalf("OutputMock.Error mock is already set by ExpectParams functions")
	}

	mmError.defaultExpectation.params = &OutputMockErrorParams{msg}
	mmError.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmError.expectations {
		if minimock.Equal(e.params, mmError.defaultExpectation.params) {
			mmError.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmError.defaultExpectation.params)
		}
	}

	return mmError
}

// ExpectMsgParam1 sets up expected param msg for Output.Error
func (mmError *mOutputMockError) ExpectMsgParam1(msg any) *mOutputMockError {
	if mmError.mock.funcError != nil {
		mmError.mock.t.Fatalf("OutputMock.Error mock is already set by Set")
	}

	if mmError.defaultExpectation == nil {
		mmError.defaultExpectation = &OutputMockErrorExpectation{}
	}

	if mmError.defaultExpectation.params != nil {
		mmError.mock.t.Fatalf("OutputMock.Error mock is already set by Expect")
	}

	if mmError.defaultExpectation.paramPtrs == nil {
		mmError.defaultExpectation.paramPtrs = &OutputMockErrorParamPtrs{}
	}
	mmError.defaultExpectation.paramPtrs.msg = &msg
	mmError.defaultExpectation.expectationOrigins.originMsg = minimock.CallerInfo(1)

	return mmError
}

// Inspect accepts an inspector function that has same arguments as the Output.Error
func (mmError *mOutputMockError) Inspect(f func(msg any)) *mOutputMockError {
	if mmError.mock.inspectFuncError != nil {
		mmError.mock.t.Fatalf("Inspect function is already set for OutputMock.Error")
	}

	mmError.mock.inspectFuncError = f

	return mmError
}

// Return sets up results that will be returned by Output.Error
func (mmError *mOutputMockError) Return() *OutputMock {
	if mmError.mock.funcError != nil {
		mmError.mock.t.Fatalf("OutputMock.Error mock is already set by Set")
	}

	if mmError.defaultExpectation == nil {
		mmError.defaultExpectation = &OutputMockErrorExpectation{mock: mmError.mock}
	}

	mmError.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmError.mock
}

// Set uses given function f to mock the Output.Error method
func (mmError *mOutputMockError) Set(f func(msg any)) *OutputMock {
	if mmError.defaultExpectation != nil {
		mmError.mock.t.Fatalf("Default expectation is already set for the Output.Error method")
	}

	if len(mmError.expectations) > 0 {
		mmError.mock.t.Fatalf("Some expectations are already set for the Output.Error method")
	}

	mmError.mock.funcError = f
	mmError.mock.funcErrorOrigin = minimock.CallerInfo(1)
	return mmError.mock
}

// When sets expectation for the Output.Error which will trigger the result defined by the following
// Then helper
func (mmError *mOutputMockError) When(msg any) *OutputMockErrorExpectation {
	if mmError.mock.funcError != nil {
		mmError.mock.t.Fatalf("OutputMock.Error mock is already set by Set")
	}

	expectation := &OutputMockErrorExpectation{
		mock:               mmError.mock,
		params:             &OutputMockErrorParams{msg},
		expectationOrigins: OutputMockErrorExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmError.expectations = append(mmError.expectations, expectation)
	return expectation
}

// Then sets up Output.Error return parameters for the expectation previously defined by the When method

func (e *OutputMockErrorExpectation) Then() *OutputMock {
	return e.mock
}

// Times sets number of times Output.Error should be invoked
func (mmError *mOutputMockError) Times(n uint64) *mOutputMockError {
	if n == 0 {
		mmError.mock.t.Fatalf("Times of OutputMock.Error mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmError.expectedInvocations, n)
	mmError.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmError
}

func (mmError *mOutputMockError) invocationsDone() bool {
	if len(mmError.expectations) == 0 && mmError.defaultExpectation == nil && mmError.mock.funcError == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmError.mock.afterErrorCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmError.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Error implements mm_contracts.Output
func (mmError *OutputMock) Error(msg any) {
	mm_atomic.AddUint64(&mmError.beforeErrorCounter, 1)
	defer mm_atomic.AddUint64(&mmError.afterErrorCounter, 1)

	mmError.t.Helper()

	if mmError.inspectFuncError != nil {
		mmError.inspectFuncError(msg)
	}

	mm_params := OutputMockErrorParams{msg}

	// Record call args
	mmError.ErrorMock.mutex.Lock()
	mmError.ErrorMock.callArgs = append(mmError.ErrorMock.callArgs, &mm_params)
	mmError.ErrorMock.mutex.Unlock()

	for _, e := range mmError.ErrorMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmError.ErrorMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmError.ErrorMock.defaultExpectation.Counter, 1)
		mm_want := mmError.ErrorMock.defaultExpectation.params
		mm_want_ptrs := mmError.ErrorMock.defaultExpectation.paramPtrs

		mm_got := OutputMockErrorParams{msg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmError.t.Errorf("OutputMock.Error got unexpected parameter msg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmError.ErrorMock.defaultExpectation.expectationOrigins.originMsg, *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmError.t.Errorf("OutputMock.Error got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmError.ErrorMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmError.funcError != nil {
		mmError.funcError(msg)
		return
	}
	mmError.t.Fatalf("Unexpected call to OutputMock.Error. %v", msg)

}

// ErrorAfterCounter returns a count of finished OutputMock.Error invocations
func (mmError *OutputMock) ErrorAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmError.afterErrorCounter)
}

// ErrorBeforeCounter returns a count of OutputMock.Error invocations
func (mmError *OutputMock) ErrorBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmError.beforeErrorCounter)
}

// Calls returns a list of arguments used in each call to OutputMock.Error.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmError *mOutputMockError) Calls() []*OutputMockErrorParams {
	mmError.mutex.RLock()

	argCopy := make([]*OutputMockErrorParams, len(mmError.callArgs))
	copy(argCopy, mmError.callArgs)

	mmError.mutex.RUnlock()

	return argCopy
}

// MinimockErrorDone returns true if the count of the Error invocations corresponds
// the number of defined expectations
func (m *OutputMock) MinimockErrorDone() bool {
	if m.ErrorMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ErrorMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ErrorMock.invocationsDone()
}

// MinimockErrorInspect logs each unmet expectation
func (m *OutputMock) MinimockErrorInspect() {
	for _, e := range m.ErrorMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OutputMock.Error at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterErrorCounter := mm_atomic.LoadUint64(&m.afterErrorCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ErrorMock.defaultExpectation != nil && afterErrorCounter < 1 {
		if m.ErrorMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OutputMock.Error at\n%s", m.ErrorMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OutputMock.Error at\n%s with params: %#v", m.ErrorMock.defaultExpectation.expectationOrigins.origin, *m.ErrorMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcError != nil && afterErrorCounter < 1 {
		m.t.Errorf("Expected call to OutputMock.Error at\n%s", m.funcErrorOrigin)
	}

	if !m.ErrorMock.invocationsDone() && afterErrorCounter > 0 {
		m.t.Errorf("Expected %d calls to OutputMock.Error at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ErrorMock.expectedInvocations), m.ErrorMock.expectedInvocationsOrigin, afterErrorCounter)
	}
}

type mOutputMockErrorf struct {
	optional           bool
	mock               *OutputMock
	defaultExpectation *OutputMockErrorfExpectation
	expectations       []*OutputMockErrorfExpectation

	callArgs []*OutputMockErrorfParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OutputMockErrorfExpectation specifies expectation struct of the Output.Errorf
type OutputMockErrorfExpectation struct {
	mock               *OutputMock
	params             *OutputMockErrorfParams
	paramPtrs          *OutputMockErrorfParamPtrs
	expectationOrigins OutputMockErrorfExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// OutputMockErrorfParams contains parameters of the Output.Errorf
type OutputMockErrorfParams struct {
	msg  string
	args []any
}

// OutputMockErrorfParamPtrs contains pointers to parameters of the Output.Errorf
type OutputMockErrorfParamPtrs struct {
	msg  *string
	args *[]any
}

// OutputMockErrorfOrigins contains origins of expectations of the Output.Errorf
type OutputMockErrorfExpectationOrigins struct {
	origin     string
	originMsg  string
	originArgs string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmErrorf *mOutputMockErrorf) Optional() *mOutputMockErrorf {
	mmErrorf.optional = true
	return mmErrorf
}

// Expect sets up expected params for Output.Errorf
func (mmErrorf *mOutputMockErrorf) Expect(msg string, args ...any) *mOutputMockErrorf {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &OutputMockErrorfExpectation{}
	}

	if mmErrorf.defaultExpectation.paramPtrs != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by ExpectParams functions")
	}

	mmErrorf.defaultExpectation.params = &OutputMockErrorfParams{msg, args}
	mmErrorf.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmErrorf.expectations {
		if minimock.Equal(e.params, mmErrorf.defaultExpectation.params) {
			mmErrorf.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmErrorf.defaultExpectation.params)
		}
	}

	return mmErrorf
}

// ExpectMsgParam1 sets up expected param msg for Output.Errorf
func (mmErrorf *mOutputMockErrorf) ExpectMsgParam1(msg string) *mOutputMockErrorf {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &OutputMockErrorfExpectation{}
	}

	if mmErrorf.defaultExpectation.params != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by Expect")
	}

	if mmErrorf.defaultExpectation.paramPtrs == nil {
		mmErrorf.defaultExpectation.paramPtrs = &OutputMockErrorfParamPtrs{}
	}
	mmErrorf.defaultExpectation.paramPtrs.msg = &msg
	mmErrorf.defaultExpectation.expectationOrigins.originMsg = minimock.CallerInfo(1)

	return mmErrorf
}

// ExpectArgsParam2 sets up expected param args for Output.Errorf
func (mmErrorf *mOutputMockErrorf) ExpectArgsParam2(args ...any) *mOutputMockErrorf {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &OutputMockErrorfExpectation{}
	}

	if mmErrorf.defaultExpectation.params != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by Expect")
	}

	if mmErrorf.defaultExpectation.paramPtrs == nil {
		mmErrorf.defaultExpectation.paramPtrs = &OutputMockErrorfParamPtrs{}
	}
	mmErrorf.defaultExpectation.paramPtrs.args = &args
	mmErrorf.defaultExpectation.expectationOrigins.originArgs = minimock.CallerInfo(1)

	return mmErrorf
}

// Inspect accepts an inspector function that has same arguments as the Output.Errorf
func (mmErrorf *mOutputMockErrorf) Inspect(f func(msg string, args ...any)) *mOutputMockErrorf {
	if mmErrorf.mock.inspectFuncErrorf != nil {
		mmErrorf.mock.t.Fatalf("Inspect function is already set for OutputMock.Errorf")
	}

	mmErrorf.mock.inspectFuncErrorf = f

	return mmErrorf
}

// Return sets up results that will be returned by Output.Errorf
func (mmErrorf *mOutputMockErrorf) Return() *OutputMock {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by Set")
	}

	if mmErrorf.defaultExpectation == nil {
		mmErrorf.defaultExpectation = &OutputMockErrorfExpectation{mock: mmErrorf.mock}
	}

	mmErrorf.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmErrorf.mock
}

// Set uses given function f to mock the Output.Errorf method
func (mmErrorf *mOutputMockErrorf) Set(f func(msg string, args ...any)) *OutputMock {
	if mmErrorf.defaultExpectation != nil {
		mmErrorf.mock.t.Fatalf("Default expectation is already set for the Output.Errorf method")
	}

	if len(mmErrorf.expectations) > 0 {
		mmErrorf.mock.t.Fatalf("Some expectations are already set for the Output.Errorf method")
	}

	mmErrorf.mock.funcErrorf = f
	mmErrorf.mock.funcErrorfOrigin = minimock.CallerInfo(1)
	return mmErrorf.mock
}

// When sets expectation for the Output.Errorf which will trigger the result defined by the following
// Then helper
func (mmErrorf *mOutputMockErrorf) When(msg string, args ...any) *OutputMockErrorfExpectation {
	if mmErrorf.mock.funcErrorf != nil {
		mmErrorf.mock.t.Fatalf("OutputMock.Errorf mock is already set by Set")
	}

	expectation := &OutputMockErrorfExpectation{
		mock:               mmErrorf.mock,
		params:             &OutputMockErrorfParams{msg, args},
		expectationOrigins: OutputMockErrorfExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmErrorf.expectations = append(mmErrorf.expectations, expectation)
	return expectation
}

// Then sets up Output.Errorf return parameters for the expectation previously defined by the When method

func (e *OutputMockErrorfExpectation) Then() *OutputMock {
	return e.mock
}

// Times sets number of times Output.Errorf should be invoked
func (mmErrorf *mOutputMockErrorf) Times(n uint64) *mOutputMockErrorf {
	if n == 0 {
		mmErrorf.mock.t.Fatalf("Times of OutputMock.Errorf mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmErrorf.expectedInvocations, n)
	mmErrorf.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmErrorf
}

func (mmErrorf *mOutputMockErrorf) invocationsDone() bool {
	if len(mmErrorf.expectations) == 0 && mmErrorf.defaultExpectation == nil && mmErrorf.mock.funcErrorf == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmErrorf.mock.afterErrorfCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmErrorf.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Errorf implements mm_contracts.Output
func (mmErrorf *OutputMock) Errorf(msg string, args ...any) {
	mm_atomic.AddUint64(&mmErrorf.beforeErrorfCounter, 1)
	defer mm_atomic.AddUint64(&mmErrorf.afterErrorfCounter, 1)

	mmErrorf.t.Helper()

	if mmErrorf.inspectFuncErrorf != nil {
		mmErrorf.inspectFuncErrorf(msg, args...)
	}

	mm_params := OutputMockErrorfParams{msg, args}

	// Record call args
	mmErrorf.ErrorfMock.mutex.Lock()
	mmErrorf.ErrorfMock.callArgs = append(mmErrorf.ErrorfMock.callArgs, &mm_params)
	mmErrorf.ErrorfMock.mutex.Unlock()

	for _, e := range mmErrorf.ErrorfMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmErrorf.ErrorfMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmErrorf.ErrorfMock.defaultExpectation.Counter, 1)
		mm_want := mmErrorf.ErrorfMock.defaultExpectation.params
		mm_want_ptrs := mmErrorf.ErrorfMock.defaultExpectation.paramPtrs

		mm_got := OutputMockErrorfParams{msg, args}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmErrorf.t.Errorf("OutputMock.Errorf got unexpected parameter msg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmErrorf.ErrorfMock.defaultExpectation.expectationOrigins.originMsg, *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

			if mm_want_ptrs.args != nil && !minimock.Equal(*mm_want_ptrs.args, mm_got.args) {
				mmErrorf.t.Errorf("OutputMock.Errorf got unexpected parameter args, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmErrorf.ErrorfMock.defaultExpectation.expectationOrigins.originArgs, *mm_want_ptrs.args, mm_got.args, minimock.Diff(*mm_want_ptrs.args, mm_got.args))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmErrorf.t.Errorf("OutputMock.Errorf got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmErrorf.ErrorfMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmErrorf.funcErrorf != nil {
		mmErrorf.funcErrorf(msg, args...)
		return
	}
	mmErrorf.t.Fatalf("Unexpected call to OutputMock.Errorf. %v %v", msg, args)

}

// ErrorfAfterCounter returns a count of finished OutputMock.Errorf invocations
func (mmErrorf *OutputMock) ErrorfAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmErrorf.afterErrorfCounter)
}

// ErrorfBeforeCounter returns a count of OutputMock.Errorf invocations
func (mmErrorf *OutputMock) ErrorfBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmErrorf.beforeErrorfCounter)
}

// Calls returns a list of arguments used in each call to OutputMock.Errorf.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmErrorf *mOutputMockErrorf) Calls() []*OutputMockErrorfParams {
	mmErrorf.mutex.RLock()

	argCopy := make([]*OutputMockErrorfParams, len(mmErrorf.callArgs))
	copy(argCopy, mmErrorf.callArgs)

	mmErrorf.mutex.RUnlock()

	return argCopy
}

// MinimockErrorfDone returns true if the count of the Errorf invocations corresponds
// the number of defined expectations
func (m *OutputMock) MinimockErrorfDone() bool {
	if m.ErrorfMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ErrorfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ErrorfMock.invocationsDone()
}

// MinimockErrorfInspect logs each unmet expectation
func (m *OutputMock) MinimockErrorfInspect() {
	for _, e := range m.ErrorfMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OutputMock.Errorf at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterErrorfCounter := mm_atomic.LoadUint64(&m.afterErrorfCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ErrorfMock.defaultExpectation != nil && afterErrorfCounter < 1 {
		if m.ErrorfMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OutputMock.Errorf at\n%s", m.ErrorfMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OutputMock.Errorf at\n%s with params: %#v", m.ErrorfMock.defaultExpectation.expectationOrigins.origin, *m.ErrorfMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcErrorf != nil && afterErrorfCounter < 1 {
		m.t.Errorf("Expected call to OutputMock.Errorf at\n%s", m.funcErrorfOrigin)
	}

	if !m.ErrorfMock.invocationsDone() && afterErrorfCounter > 0 {
		m.t.Errorf("Expected %d calls to OutputMock.Errorf at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ErrorfMock.expectedInvocations), m.ErrorfMock.expectedInvocationsOrigin, afterErrorfCounter)
	}
}

type mOutputMockInfo struct {
	optional           bool
	mock               *OutputMock
	defaultExpectation *OutputMockInfoExpectation
	expectations       []*OutputMockInfoExpectation

	callArgs []*OutputMockInfoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OutputMockInfoExpectation specifies expectation struct of the Output.Info
type OutputMockInfoExpectation struct {
	mock               *OutputMock
	params             *OutputMockInfoParams
	paramPtrs          *OutputMockInfoParamPtrs
	expectationOrigins OutputMockInfoExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// OutputMockInfoParams contains parameters of the Output.Info
type OutputMockInfoParams struct {
	msg any
}

// OutputMockInfoParamPtrs contains pointers to parameters of the Output.Info
type OutputMockInfoParamPtrs struct {
	msg *any
}

// OutputMockInfoOrigins contains origins of expectations of the Output.Info
type OutputMockInfoExpectationOrigins struct {
	origin    string
	originMsg string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInfo *mOutputMockInfo) Optional() *mOutputMockInfo {
	mmInfo.optional = true
	return mmInfo
}

// Expect sets up expected params for Output.Info
func (mmInfo *mOutputMockInfo) Expect(msg any) *mOutputMockInfo {
	if mmInfo.mock.funcInfo != nil {
		mmInfo.mock.t.Fatalf("OutputMock.Info mock is already set by Set")
	}

	if mmInfo.defaultExpectation == nil {
		mmInfo.defaultExpectation = &OutputMockInfoExpectation{}
	}

	if mmInfo.defaultExpectation.paramPtrs != nil {
		mmInfo.mock.t.Fatalf("OutputMock.Info mock is already set by ExpectParams functions")
	}

	mmInfo.defaultExpectation.params = &OutputMockInfoParams{msg}
	mmInfo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInfo.expectations {
		if minimock.Equal(e.params, mmInfo.defaultExpectation.params) {
			mmInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInfo.defaultExpectation.params)
		}
	}

	return mmInfo
}

// ExpectMsgParam1 sets up expected param msg for Output.Info
func (mmInfo *mOutputMockInfo) ExpectMsgParam1(msg any) *mOutputMockInfo {
	if mmInfo.mock.funcInfo != nil {
		mmInfo.mock.t.Fatalf("OutputMock.Info mock is already set by Set")
	}

	if mmInfo.defaultExpectation == nil {
		mmInfo.defaultExpectation = &OutputMockInfoExpectation{}
	}

	if mmInfo.defaultExpectation.params != nil {
		mmInfo.mock.t.Fatalf("OutputMock.Info mock is already set by Expect")
	}

	if mmInfo.defaultExpectation.paramPtrs == nil {
		mmInfo.defaultExpectation.paramPtrs = &OutputMockInfoParamPtrs{}
	}
	mmInfo.defaultExpectation.paramPtrs.msg = &msg
	mmInfo.defaultExpectation.expectationOrigins.originMsg = minimock.CallerInfo(1)

	return mmInfo
}

// Inspect accepts an inspector function that has same arguments as the Output.Info
func (mmInfo *mOutputMockInfo) Inspect(f func(msg any)) *mOutputMockInfo {
	if mmInfo.mock.inspectFuncInfo != nil {
		mmInfo.mock.t.Fatalf("Inspect function is already set for OutputMock.Info")
	}

	mmInfo.mock.inspectFuncInfo = f

	return mmInfo
}

// Return sets up results that will be returned by Output.Info
func (mmInfo *mOutputMockInfo) Return() *OutputMock {
	if mmInfo.mock.funcInfo != nil {
		mmInfo.mock.t.Fatalf("OutputMock.Info mock is already set by Set")
	}

	if mmInfo.defaultExpectation == nil {
		mmInfo.defaultExpectation = &OutputMockInfoExpectation{mock: mmInfo.mock}
	}

	mmInfo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInfo.mock
}

// Set uses given function f to mock the Output.Info method
func (mmInfo *mOutputMockInfo) Set(f func(msg any)) *OutputMock {
	if mmInfo.defaultExpectation != nil {
		mmInfo.mock.t.Fatalf("Default expectation is already set for the Output.Info method")
	}

	if len(mmInfo.expectations) > 0 {
		mmInfo.mock.t.Fatalf("Some expectations are already set for the Output.Info method")
	}

	mmInfo.mock.funcInfo = f
	mmInfo.mock.funcInfoOrigin = minimock.CallerInfo(1)
	return mmInfo.mock
}

// When sets expectation for the Output.Info which will trigger the result defined by the following
// Then helper
func (mmInfo *mOutputMockInfo) When(msg any) *OutputMockInfoExpectation {
	if mmInfo.mock.funcInfo != nil {
		mmInfo.mock.t.Fatalf("OutputMock.Info mock is already set by Set")
	}

	expectation := &OutputMockInfoExpectation{
		mock:               mmInfo.mock,
		params:             &OutputMockInfoParams{msg},
		expectationOrigins: OutputMockInfoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInfo.expectations = append(mmInfo.expectations, expectation)
	return expectation
}

// Then sets up Output.Info return parameters for the expectation previously defined by the When method

func (e *OutputMockInfoExpectation) Then() *OutputMock {
	return e.mock
}

// Times sets number of times Output.Info should be invoked
func (mmInfo *mOutputMockInfo) Times(n uint64) *mOutputMockInfo {
	if n == 0 {
		mmInfo.mock.t.Fatalf("Times of OutputMock.Info mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInfo.expectedInvocations, n)
	mmInfo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInfo
}

func (mmInfo *mOutputMockInfo) invocationsDone() bool {
	if len(mmInfo.expectations) == 0 && mmInfo.defaultExpectation == nil && mmInfo.mock.funcInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInfo.mock.afterInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Info implements mm_contracts.Output
func (mmInfo *OutputMock) Info(msg any) {
	mm_atomic.AddUint64(&mmInfo.beforeInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmInfo.afterInfoCounter, 1)

	mmInfo.t.Helper()

	if mmInfo.inspectFuncInfo != nil {
		mmInfo.inspectFuncInfo(msg)
	}

	mm_params := OutputMockInfoParams{msg}

	// Record call args
	mmInfo.InfoMock.mutex.Lock()
	mmInfo.InfoMock.callArgs = append(mmInfo.InfoMock.callArgs, &mm_params)
	mmInfo.InfoMock.mutex.Unlock()

	for _, e := range mmInfo.InfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmInfo.InfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInfo.InfoMock.defaultExpectation.Counter, 1)
		mm_want := mmInfo.InfoMock.defaultExpectation.params
		mm_want_ptrs := mmInfo.InfoMock.defaultExpectation.paramPtrs

		mm_got := OutputMockInfoParams{msg}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.msg != nil && !minimock.Equal(*mm_want_ptrs.msg, mm_got.msg) {
				mmInfo.t.Errorf("OutputMock.Info got unexpected parameter msg, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInfo.InfoMock.defaultExpectation.expectationOrigins.originMsg, *mm_want_ptrs.msg, mm_got.msg, minimock.Diff(*mm_want_ptrs.msg, mm_got.msg))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInfo.t.Errorf("OutputMock.Info got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInfo.InfoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmInfo.funcInfo != nil {
		mmInfo.funcInfo(msg)
		return
	}
	mmInfo.t.Fatalf("Unexpected call to OutputMock.Info. %v", msg)

}

// InfoAfterCounter returns a count of finished OutputMock.Info invocations
func (mmInfo *OutputMock) InfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInfo.afterInfoCounter)
}

// InfoBeforeCounter returns a count of OutputMock.Info invocations
func (mmInfo *OutputMock) InfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInfo.beforeInfoCounter)
}

// Calls returns a list of arguments used in each call to OutputMock.Info.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInfo *mOutputMockInfo) Calls() []*OutputMockInfoParams {
	mmInfo.mutex.RLock()

	argCopy := make([]*OutputMockInfoParams, len(mmInfo.callArgs))
	copy(argCopy, mmInfo.callArgs)

	mmInfo.mutex.RUnlock()

	return argCopy
}

// MinimockInfoDone returns true if the count of the Info invocations corresponds
// the number of defined expectations
func (m *OutputMock) MinimockInfoDone() bool {
	if m.InfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InfoMock.invocationsDone()
}

// MinimockInfoInspect logs each unmet expectation
func (m *OutputMock) MinimockInfoInspect() {
	for _, e := range m.InfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OutputMock.Info at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInfoCounter := mm_atomic.LoadUint64(&m.afterInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InfoMock.defaultExpectation != nil && afterInfoCounter < 1 {
		if m.InfoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OutputMock.Info at\n%s", m.InfoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OutputMock.Info at\n%s with params: %#v", m.InfoMock.defaultExpectation.expectationOrigins.origin, *m.InfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInfo != nil && afterInfoCounter < 1 {
		m.t.Errorf("Expected call to OutputMock.Info at\n%s", m.funcInfoOrigin)
	}

	if !m.InfoMock.invocationsDone() && afterInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to OutputMock.Info at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InfoMock.expectedInvocations), m.InfoMock.expectedInvocationsOrigin, afterInfoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OutputMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockErrorInspect()

			m.MinimockErrorfInspect()

			m.MinimockInfoInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OutputMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OutputMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockErrorDone() &&
		m.MinimockErrorfDone() &&
		m.MinimockInfoDone()
}
