name: Go

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - &fast-clone
        name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - *fast-clone

      - &setup-go
        name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -tags release -timeout 1m -race -v -coverprofile=coverage.out ./...

      - name: Upload code coverage
        uses: actions/upload-artifact@v7
        with:
          name: code-coverage
          path: coverage.out

  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - *fast-clone

      - *setup-go

      - name: Build
        run: go build -tags release -v .

  sonar-scan:
    name: SonarCloud Scan
    needs: [ test, build, lint ]
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - *fast-clone

      - name: Download code coverage
        uses: actions/download-artifact@v8
        with:
          name: code-coverage
          path: .

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  code-ql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: go
          build-mode: autobuild
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: /language:go
